---
spring:
    application:
        name: CF-WORKSHOP-SPRING-BOOT
    jpa:
        hibernate:
            ddl-auto: create
    cloud:
        services:
            registrationMethod: route
security:
    basic:
        enabled: false
logging:
    level:
        org:
            springframework:
                web: INFO
        io:
            pivotal: DEBUG
        com:
            netflix:
                discovery: DEBUG