---
spring:
    application:
        name: CF-WORKSHOP-SPRING-BOOT
    jpa:
        hibernate:
            ddl-auto: create
logging:
    level:
        org:
            springframework:
                web: INFO
        io:
            pivotal: DEBUG
eureka:
    client:
        serviceUrl:
            defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka
    instance:
        metadataMap:
            instanceId: ${vcap.application.instance_id:${spring.application.name}:${vcap.application.instance_id:${server.port}}}
