---
resources:
- name: cf-workshop-demo
  type: git
  source:
    uri: https://github.com/bjimerson-pivotal/cf-workshop-demo
    branch: master

jobs:
- name: package-app
  plan:
  - get: cf-workshop-demo
  - task: package
    file: cf-workshop-demo/ci/tasks/package.yml
